name: myfirstpipeline2

on:
  workflow_dispatch:

jobs:
  clone-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Clone public repo via HTTPS
        uses: chihqiang/checkout-action@main
        with:
          repo: https://github.com/GEETHA9999/DevOPS-.git
          branch: main
